// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjPrfiW8OVLGWEMLE22iae3_mhi-7QAGI',
    appId: '1:716245733456:web:63b6f7fc5fba95bc7cc155',
    messagingSenderId: '716245733456',
    projectId: 'smartplaza-12656',
    authDomain: 'smartplaza-12656.firebaseapp.com',
    storageBucket: 'smartplaza-12656.firebasestorage.app',
    measurementId: 'G-T4XTB539Y9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQt87G65kU80_lMQuqDcLFTvmQzCIF9ms',
    appId: '1:716245733456:android:f021aeaf5f0434f47cc155',
    messagingSenderId: '716245733456',
    projectId: 'smartplaza-12656',
    storageBucket: 'smartplaza-12656.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUlBFEUpvILBP2ckVKiMdqyTPWcI8gl9o',
    appId: '1:716245733456:ios:d20805405b4aff827cc155',
    messagingSenderId: '716245733456',
    projectId: 'smartplaza-12656',
    storageBucket: 'smartplaza-12656.firebasestorage.app',
    iosBundleId: 'com.example.smartPlaza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUlBFEUpvILBP2ckVKiMdqyTPWcI8gl9o',
    appId: '1:716245733456:ios:d20805405b4aff827cc155',
    messagingSenderId: '716245733456',
    projectId: 'smartplaza-12656',
    storageBucket: 'smartplaza-12656.firebasestorage.app',
    iosBundleId: 'com.example.smartPlaza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjPrfiW8OVLGWEMLE22iae3_mhi-7QAGI',
    appId: '1:716245733456:web:c935360aea023e847cc155',
    messagingSenderId: '716245733456',
    projectId: 'smartplaza-12656',
    authDomain: 'smartplaza-12656.firebaseapp.com',
    storageBucket: 'smartplaza-12656.firebasestorage.app',
    measurementId: 'G-050T9MPNDW',
  );
}
